#:schema node_modules/wrangler/config-schema.json
name = "wav-miniapp"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Automatically place your workloads in an optimal location to minimize latency.
# If you are running back-end logic in a Pages Function, running it closer to your back-end infrastructure
# rather than the end user may result in better performance.
# Docs: https://developers.cloudflare.com/pages/functions/smart-placement/#smart-placement
[placement]
mode = "smart"


######## PREVIEW environment config ########
[env.preview.vars]
# API_KEY = "xyz789"
NODE_VERSION = "18.17.0"
NEXT_PUBLIC_ENV="test"
NEXT_PUBLIC_BASE_URL="https://develop.wav-miniapp.pages.dev" 
NEXT_PUBLIC_API_TG_URL="https://develop.wav-miniapp.pages.dev" 
NEXT_PUBLIC_TG_GROUP_URL="https://t.me/chx_test_group" 
NEXT_PUBLIC_ICONFONT_URL="https://cdn2.codesign.qq.com/icons/86jzxNyr6YN5n0b/latest/iconfont.css"
NEXT_DEBUG = "true"



######## PRODUCTION environment config ########

[env.production.vars]
NODE_VERSION = "18.17.0"
NEXT_PUBLIC_BASE_URL="https://develop.wav-miniapp.pages.dev" 
NEXT_PUBLIC_API_TG_URL="https://develop.wav-miniapp.pages.dev" 
NEXT_PUBLIC_TG_GROUP_URL="https://t.me/chx_test_group" 
NEXT_PUBLIC_ICONFONT_URL="https://cdn2.codesign.qq.com/icons/86jzxNyr6YN5n0b/latest/iconfont.css"

