export const LOCAL_STORAGE_TOKEN = 'ACCESS_TOKEN';
export const LOCAL_STORAGE_NEW_USER = 'NEW_USER';
export const LOCAL_STORAGE_PROFILE = 'USER_PROFILE';
export const LOCAL_STORAGE_APP_USER = 'APP_USER';

export const LOCAL_STORAGE_USER_WALLET = 'USER_WALLET';
export const LOCAL_STORAGE_LEVEL_CONFIG = 'LEVEL_CONFIG';
export const LOCAL_STORAGE_REFERRAL_COUNT = 'REFERRAL_COUNT';
export const LOCAL_STORAGE_TODAY_REWARD = 'TODAY_REWARD';
export const LOCAL_STORAGE_BOOSTER = 'BOOSTER';
export const LOCAL_STORAGE_CAI = 'CAI';
export const LOCAL_STORAGE_DAILY_ENERGY = 'DAILY_ENERGY';
export const SESSION_STORAGE_EXPLORE_SCROLL_TOP = 'TEMP_EXPLORE_SCROLL_TOP';
export const SESSION_STORAGE_EXPLORE_LIST = 'TEMP_EXPLORE_LIST';
export const SESSION_STORAGE_LIST_HAS_MORE = 'TEMP_EXPLORE_LIST_HAS_MORE';
export const SESSION_STORAGE_LIST_PAGE = 'TEMP_EXPLORE_LIST_PAGE';

export const COOKIES_TOKEN = 'ACCESS_TOKEN';

export const INVITE_CODE = 'INVITE_CODE';
