import { ICardItem } from '@/types';

export const instruments: ICardItem[] = [
  {
    id: '6',
    name: 'Drum',
    level: 0,
    profitPerHour: 50,
    upgradeCost: 1000,
    icon: 'https://d121vty759npai.cloudfront.net/images/adaa2b56bb9b4412b10a6366eeca31ab.jpeg',
    isLocked: true,
    unlockRequirement: 'Invite 3 friends',
    maxLevel: 5,
    nextLevelProfitPerHour: 300,
    description:
      'When the music flows out from its sound-producing unit, the full and rich timbre seems like a musician playing personally by your ear.',
  },
  {
    id: '1',
    name: 'Violin',
    level: 5,
    profitPerHour: 100,
    upgradeCost: 1000,
    icon: 'https://d121vty759npai.cloudfront.net/images/adaa2b56bb9b4412b10a6366eeca31ab.jpeg',
    isLocked: false,
    unlockRequirement: 'Invite 3 friends',
    maxLevel: 5,
    nextLevelProfitPerHour: 400,
    description:
      'When the music flows out from its sound-producing unit, the full and rich timbre seems like a musician playing personally by your ear.',
  },
  {
    id: '2',
    name: 'Paino',
    level: 1,
    profitPerHour: 200,
    upgradeCost: 12000,
    icon: 'https://d121vty759npai.cloudfront.net/images/adaa2b56bb9b4412b10a6366eeca31ab.jpeg',
    isLocked: false,
    unlockRequirement: '123456',
    nextLevelProfitPerHour: 500,
    description:
      'When the music flows out from its sound-producing unit, the full and rich timbre seems like a musician playing personally by your ear.',
  },
  {
    id: '3',
    name: 'Guitar',
    level: 1,
    profitPerHour: 400,
    upgradeCost: 1000,
    icon: 'https://d121vty759npai.cloudfront.net/images/adaa2b56bb9b4412b10a6366eeca31ab.jpeg',
    isLocked: false,
    unlockRequirement: '',
    nextLevelProfitPerHour: 600,
    description:
      'When the music flows out from its sound-producing unit, the full and rich timbre seems like a musician playing personally by your ear.',
  },
  {
    id: '4',
    name: 'Flute',
    level: 1,
    profitPerHour: 600,
    upgradeCost: 1000,
    icon: 'https://d121vty759npai.cloudfront.net/images/adaa2b56bb9b4412b10a6366eeca31ab.jpeg',
    isLocked: false,
    unlockRequirement: '',
    nextLevelProfitPerHour: 700,
    description:
      'When the music flows out from its sound-producing unit, the full and rich timbre seems like a musician playing personally by your ear.',
  },
  {
    id: '5',
    name: 'Cello',
    level: 1,
    profitPerHour: 800,
    upgradeCost: 1000,
    icon: 'https://d121vty759npai.cloudfront.net/images/adaa2b56bb9b4412b10a6366eeca31ab.jpeg',
    isLocked: false,
    unlockRequirement: '',
    nextLevelProfitPerHour: 800,
    description:
      'When the music flows out from its sound-producing unit, the full and rich timbre seems like a musician playing personally by your ear.',
  },
  {
    id: '7',
    name: 'Harp',
    level: 1,
    profitPerHour: 1000,
    upgradeCost: 1000,
    icon: 'https://d121vty759npai.cloudfront.net/images/adaa2b56bb9b4412b10a6366eeca31ab.jpeg',
    isLocked: false,
    unlockRequirement: '',
    nextLevelProfitPerHour: 900,
    description:
      'When the music flows out from its sound-producing unit, the full and rich timbre seems like a musician playing personally by your ear.',
  },
  {
    id: '8',
    name: 'New Wave',
    level: 0,
    profitPerHour: 50,
    upgradeCost: 1000,
    icon: 'https://d121vty759npai.cloudfront.net/images/adaa2b56bb9b4412b10a6366eeca31ab.jpeg',
    isLocked: true,
    unlockRequirement: 'Invite 3 friends',
    maxLevel: 5,
    nextLevelProfitPerHour: 30,
    description:
      'When the music flows out from its sound-producing unit, the full and rich timbre seems like a musician playing personally by your ear.',
  },
  {
    id: '9',
    name: 'New Wave',
    level: 0,
    profitPerHour: 50,
    upgradeCost: 1000,
    icon: 'https://d121vty759npai.cloudfront.net/images/adaa2b56bb9b4412b10a6366eeca31ab.jpeg',
    isLocked: true,
    unlockRequirement: 'Invite 3 friends',
    maxLevel: 5,
    nextLevelProfitPerHour: 30,
    description:
      'When the music flows out from its sound-producing unit, the full and rich timbre seems like a musician playing personally by your ear.',
  },
  {
    id: '10',
    name: 'New Wave',
    level: 0,
    profitPerHour: 50,
    upgradeCost: 1000,
    icon: 'https://d121vty759npai.cloudfront.net/images/adaa2b56bb9b4412b10a6366eeca31ab.jpeg',
    isLocked: true,
    unlockRequirement: 'Invite 3 friends',
    maxLevel: 5,
    nextLevelProfitPerHour: 30,
    description:
      'When the music flows out from its sound-producing unit, the full and rich timbre seems like a musician playing personally by your ear.',
  },
];

export const styles: ICardItem[] = [
  {
    id: '18',
    name: 'New Wave',
    level: 0,
    profitPerHour: 50,
    upgradeCost: 1000,
    icon: 'https://d121vty759npai.cloudfront.net/images/adaa2b56bb9b4412b10a6366eeca31ab.jpeg',
    isLocked: true,
    unlockRequirement: 'Invite 3 friends',
    maxLevel: 5,
    nextLevelProfitPerHour: 30,
    description:
      'When the music flows out from its sound-producing unit, the full and rich timbre seems like a musician playing personally by your ear.',
  },
  {
    id: '21',
    name: 'POP',
    level: 5,
    profitPerHour: 200,
    upgradeCost: 1000,
    icon: 'https://d121vty759npai.cloudfront.net/images/adaa2b56bb9b4412b10a6366eeca31ab.jpeg',
    isLocked: false,
    unlockRequirement: 'Invite 3 friends',
    maxLevel: 5,
    nextLevelProfitPerHour: 60,
    description:
      'When the music flows out from its sound-producing unit, the full and rich timbre seems like a musician playing personally by your ear.',
  },
  {
    id: '32',
    name: 'JAZZ',
    level: 1,
    profitPerHour: 100,
    upgradeCost: 12000,
    icon: 'https://d121vty759npai.cloudfront.net/images/adaa2b56bb9b4412b10a6366eeca31ab.jpeg',
    isLocked: false,
    unlockRequirement: '123456',
    nextLevelProfitPerHour: 90,
    description:
      'When the music flows out from its sound-producing unit, the full and rich timbre seems like a musician playing personally by your ear.',
  },
  {
    id: '43',
    name: 'R&B',
    level: 1,
    profitPerHour: 10,
    upgradeCost: 600,
    icon: 'https://d121vty759npai.cloudfront.net/images/adaa2b56bb9b4412b10a6366eeca31ab.jpeg',
    isLocked: false,
    unlockRequirement: '',
    nextLevelProfitPerHour: 300,
    description:
      'When the music flows out from its sound-producing unit, the full and rich timbre seems like a musician playing personally by your ear.',
  },
];
